language: node_js

node_js:
  - 10

before_install:
  - git remote rm origin
  - git remote add origin "https://symbology:$GITHUB_TOKEN@github.com/jshor/symbology.git"

script:
  - echo "$TRAVIS_BRANCH"
  - yarn test
  - yarn docs
  - yarn build

after_success:
  - if [[ $TRAVIS_BRANCH == "master" && $TRAVIS_COMMIT_MESSAGE != *"chore(release)"* ]]; then
      yarn release;
      yarn codecov;
      git push --follow-tags origin master;

      if [[ $TRAVIS_COMMIT_MESSAGE != *"chore(release)"* ]]; then
        cd "$TRAVIS_BUILD_DIR";
        cd docs;
        git init;
        git checkout -b gh-pages;
        git add . ;
        git -c user.name='Travis CI' -c user.email='Travis CI' commit -m "Documentation";
        git push -f origin gh-pages &>/dev/null;
        cd "$TRAVIS_BUILD_DIR";
      fi
    fi
    
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    tags: true