language: node_js
sudo: required
before_install:
  - export CHROME_BIN=chromium-browser
  - export CHROME_BIN=firefox
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
node_js:
  - 0.10
script:
  - npm install -g bower
  - bower install
<<<<<<< HEAD
  - npm test
=======
  - npm test

after_success: 
- cat ./coverage/**/lcov.info | ./node_modules/coveralls/bin/coveralls.js
>>>>>>> 3793ba7... adds coverage info to gitignore
