language: node_js
sudo: required
before_install:
  - export PHANTOMJS_EXECUTABLE='phantomjs --local-to-remote-url-access=yes --ignore-ssl-errors=yes'
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
node_js:
  - 0.10
script:
  - npm install -g bower
  - bower install
  - npm test