language: node_js

node_js:
  - 10

before_install:
  - git remote rm origin
  - git remote add origin "https://symbology:$GITHUB_TOKEN@github.com/jshor/datebook.git"

script:
  - echo "$TRAVIS_BRANCH"
  - yarn test
  - yarn docs
  - yarn build

after_success:
  - if [[ $TRAVIS_BRANCH == "master" && $TRAVIS_COMMIT_MESSAGE != *"chore(release)"* ]]; then
      yarn release;
      git log -1 --pretty=%B ;
      git push --follow-tags origin HEAD:master;

    fi
    
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    tags: true